### ISSUE TITLE
DSP48E1 simulation Fails on Combinational designs

### ISSUE THREAD

**Issue by vcanumalla** [uwsampl/lakeroad-evaluation#156]
Issue that encapsulates the debugging for DSP48e1. I wasnt able to finish debugging the semantics extraction errors in the modified for racket module, and I likely won't have time to work on this full time. Happy to help others who want to fix this.

Currently:

- combinational tests fail verilator simulation. Usually, the error is that the ground-truth module and the actual synthesized output differ by exactly 1.

This PR adds some very-hacky addition for dsp48e1 tests to be ran (basically just copy-pasted dsp48e2 python code and changed name to virtex). _It only adds tests for lakeroad synthesis and simulation, NOT vivado_. In other words, you can run robustness experiments for lakeroad mapping to DSP48e1, but you will not be able to generate graphs, run vivado, yosys, etc. for dsp48e1.

Let me know if you have any questions or help, I'll do my best to answer anything

**Comment by gussmith23** [comment]
Fixed in https://github.com/uwsampl/lakeroad/pull/427
